version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Build started"
      - echo "Running application check"
      - node app.js &
      - sleep 5
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
